package com.mycompany.sistemadeventaseinventario.Presentacion.Modulos.FormsEdit;

import com.mycompany.sistemadeventaseinventario.DAOImplementacion.DAOProductoImpl;
import com.mycompany.sistemadeventaseinventario.DAOImplementacion.DAOProveedoresImpl;
import com.mycompany.sistemadeventaseinventario.Presentacion.Modulos.Inventario;
import com.mycompany.sistemadeventaseinventario.Entidades.Producto;
import com.mycompany.sistemadeventaseinventario.Entidades.Proveedor;
import com.mycompany.sistemadeventaseinventario.PersistenciaDAO.DAOProducto;
import com.mycompany.sistemadeventaseinventario.PersistenciaDAO.DAOProveedores;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Frank
 */
public class EditProduct extends javax.swing.JDialog {

    DAOProveedores dao = new DAOProveedoresImpl();
    private final Inventario ventanaInventario;
    int Id_producto;

    public EditProduct(JFrame ventana, Inventario inven, int id_prodcuto, String nombre, String marca, int stock, double precio, String proveedor, String observacion) {
        super(ventana, "Editar Producto", true);
        setLocationRelativeTo(ventana);
        this.ventanaInventario = inven;
        initComponents();
        mostrarProveedoresEnCB();
        txtEditName.setText(nombre);
        txtEditMarca.setText(marca);
        txtxEditStock.setText(String.valueOf(stock));
        txtEditPrecio.setText(String.valueOf(precio));
        txeditObs.setText(observacion);
        CBeditProv.setSelectedItem(proveedor);
        txtEditName.requestFocus();
        Id_producto = id_prodcuto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtEditName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEditMarca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtxEditIDProveedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtxEditStock = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEditPrecio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txeditObs = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        btnGuardarEdit = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        CBeditProv = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(242, 242, 242));

        jSeparator1.setBackground(new java.awt.Color(242, 242, 242));
        jSeparator1.setForeground(new java.awt.Color(242, 242, 242));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 37, 41));
        jLabel2.setText("Nombre del producto :");

        txtEditName.setBackground(new java.awt.Color(254, 254, 254));
        txtEditName.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtEditName.setForeground(new java.awt.Color(51, 51, 51));
        txtEditName.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(33, 37, 41));
        jLabel3.setText("Marca del producto : ");

        txtEditMarca.setBackground(new java.awt.Color(254, 254, 254));
        txtEditMarca.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtEditMarca.setForeground(new java.awt.Color(51, 51, 51));
        txtEditMarca.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(33, 37, 41));
        jLabel4.setText("ID de proveedor :");

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(33, 37, 41));
        jLabel5.setText("Proveedor : ");

        txtxEditIDProveedor.setEditable(false);
        txtxEditIDProveedor.setBackground(new java.awt.Color(254, 254, 254));
        txtxEditIDProveedor.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtxEditIDProveedor.setForeground(new java.awt.Color(51, 51, 51));
        txtxEditIDProveedor.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(33, 37, 41));
        jLabel6.setText("Precio :  S/.");

        txtxEditStock.setBackground(new java.awt.Color(254, 254, 254));
        txtxEditStock.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtxEditStock.setForeground(new java.awt.Color(51, 51, 51));
        txtxEditStock.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(33, 37, 41));
        jLabel7.setText("Stock : ");

        txtEditPrecio.setBackground(new java.awt.Color(254, 254, 254));
        txtEditPrecio.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtEditPrecio.setForeground(new java.awt.Color(51, 51, 51));
        txtEditPrecio.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(33, 37, 41));
        jLabel8.setText("Observaciones : ");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txeditObs.setBackground(new java.awt.Color(254, 254, 254));
        txeditObs.setColumns(20);
        txeditObs.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txeditObs.setForeground(new java.awt.Color(51, 51, 51));
        txeditObs.setRows(5);
        txeditObs.setBorder(null);
        jScrollPane1.setViewportView(txeditObs);

        jSeparator2.setBackground(new java.awt.Color(242, 242, 242));
        jSeparator2.setForeground(new java.awt.Color(242, 242, 242));

        btnGuardarEdit.setBackground(new java.awt.Color(52, 152, 219));
        btnGuardarEdit.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnGuardarEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources_img/save_30dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btnGuardarEdit.setText("Guardar");
        btnGuardarEdit.setBorder(null);
        btnGuardarEdit.setBorderPainted(false);
        btnGuardarEdit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGuardarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEditActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(108, 117, 125));
        jButton3.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources_img/close_30dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.setBorder(null);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        CBeditProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBeditProvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEditName)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEditMarca)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtEditPrecio)
                                            .addComponent(txtxEditIDProveedor, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtxEditStock)
                                            .addComponent(CBeditProv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE))))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEditName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEditMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CBeditProv, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtxEditIDProveedor))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtxEditStock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarProveedoresEnCB() {
        try {
            List<String> proveedoresName = dao.obtenerNombresEmpresas();

            CBeditProv.removeAllItems();

            for (String nombre : proveedoresName) {

                CBeditProv.addItem(nombre);
            }

        } catch (Exception e) {
        }

    }


    private void btnGuardarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEditActionPerformed

        String nombre, marca, proveedor, observaciones;
        int id_proveedor, stock;
        double precio;
        Proveedor prov = new Proveedor();

        if (txtEditName.getText().isEmpty() || txtEditMarca.getText().isEmpty() || txtEditPrecio.getText().isEmpty() || txtxEditStock.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar los campos", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        nombre = txtEditName.getText();
        marca = txtEditMarca.getText();
        proveedor = CBeditProv.getSelectedItem().toString();
        observaciones = txeditObs.getText();
        id_proveedor = Integer.parseInt(txtxEditIDProveedor.getText());
        stock = Integer.parseInt(txtxEditStock.getText());
        precio = Double.parseDouble(txtEditPrecio.getText());

        try {

            DAOProveedores daoprov = new DAOProveedoresImpl();
            prov = daoprov.traerProveedor(id_proveedor);

            Producto NuevoProd = new Producto();

            NuevoProd.setNombre(nombre);
            NuevoProd.setMarca(marca);
            NuevoProd.setStock(stock);
            NuevoProd.setPrecio(precio);
            NuevoProd.setObservacion(observaciones);
            NuevoProd.setProovedor(prov);

            DAOProducto daoProd = new DAOProductoImpl();
            daoProd.Editar(Id_producto, NuevoProd, prov);
            JOptionPane.showMessageDialog(this, "Se actualizarón los datos del producto", "DATOS ACTUALIZADOS", JOptionPane.INFORMATION_MESSAGE);
            ventanaInventario.CargarTablaInventario();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al actualizar: " + e.getMessage(), "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnGuardarEditActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void CBeditProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBeditProvActionPerformed

        try {
            List<Proveedor> listaProveedores = dao.listarProveedores();
            String nombreSeleccionado = (String) CBeditProv.getSelectedItem();

            for (Proveedor p : listaProveedores) {
                if (p.getEmpresa().equals(nombreSeleccionado)) {
                    txtxEditIDProveedor.setText(String.valueOf(p.getId_proveedor()));
                    break;
                }
            }
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_CBeditProvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBeditProv;
    private javax.swing.JButton btnGuardarEdit;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea txeditObs;
    private javax.swing.JTextField txtEditMarca;
    private javax.swing.JTextField txtEditName;
    private javax.swing.JTextField txtEditPrecio;
    private javax.swing.JTextField txtxEditIDProveedor;
    private javax.swing.JTextField txtxEditStock;
    // End of variables declaration//GEN-END:variables
}
