package com.mycompany.sistemadeventaseinventario.Presentacion.Login;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTMaterialLighterIJTheme;
import com.mycompany.sistemadeventaseinventario.DAOImplementacion.DAOUsuariosImpl;
import com.mycompany.sistemadeventaseinventario.Presentacion.Principal.Principal;
import com.mycompany.sistemadeventaseinventario.Entidades.Usuario;
import com.mycompany.sistemadeventaseinventario.PersistenciaDAO.DAOUsuarios;
import java.awt.Color;
import java.awt.Taskbar;
import java.awt.image.BufferedImage;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
//import javax.swing.SwingUtilities;

/**
 * Ventana de inicio de sesión del sistema de ventas e inventario.
 *
 * En esta clase se codifica la interfaz gráfica de login para los usuarios del
 * sistema. Permite validar credenciales y abrir la ventana principal si son
 * correctas. También gestiona eventos de la ventana como cerrar, minimizar y
 * mover.
 *
 * @author Frank
 */
public class Login extends javax.swing.JFrame {

    /**
     * Coordenadas del mouse para permitir arrastrar la ventana
     */
    int xMouse, yMouse;

    /**
     * Constructor principal. Inicializa componentes y aplica estilos.
     */
    public Login() {

        initComponents();
        initStylles();
        iconoEnBarraTareas();
    }

    /**
     * Aplica estilos iniciales a la ventana y configura el tema visual FlatLaf.
     */
    private void initStylles() {
        iniciarSesion.requestFocus();
        FlatMTMaterialLighterIJTheme.setup();
    }

    private void iconoEnBarraTareas() {

        try {
            String iconPath = "/resources_img/Logo-ferreteri.png"; 
            URL iconURL = getClass().getResource(iconPath);

            if (iconURL != null) {
                BufferedImage image = ImageIO.read(iconURL);

                // 1. Establece el icono para la ventana 
                setIconImage(image);

                // 2. establecer el icono para la barra de tareas (con la validación correcta)
                // Primero, verificamos si la barra de tareas existe.
                if (Taskbar.isTaskbarSupported()) {
                    Taskbar taskbar = Taskbar.getTaskbar();

                    // verificamos si la *funcionalidad específica* de cambiar el icono es compatible.
                    if (taskbar.isSupported(Taskbar.Feature.ICON_IMAGE)) {
                        taskbar.setIconImage(image);
                        System.out.println("Icono de la barra de tareas configurado exitosamente.");
                    } else {
                        System.out.println("La funcionalidad de icono en la barra de tareas no es compatible en este entorno (ej: corriendo desde el IDE).");
                    }
                }
            } else {
                System.err.println("Error: No se pudo encontrar el icono en la ruta: " + iconPath);
            }
        } catch (Exception e) {
            System.err.println("Error al cargar el icono de la aplicación: " + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BackGround = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelXClose = new javax.swing.JPanel();
        btnclose = new javax.swing.JLabel();
        panelminimize = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        iniciarSesion = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        paswordUser = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        HeaderExit = new javax.swing.JPanel();
        btnIniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setPreferredSize(new java.awt.Dimension(800, 500));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(11, 33, 56));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources_img/KENKER-LOGO (1).png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 210, 150));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 127, 27));
        jLabel1.setText("FERRETERIA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 140, 40));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(235, 243, 255));
        jLabel4.setText("EL YUNQUE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 250, 70));

        jLabel2.setBackground(new java.awt.Color(20, 63, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources_img/fondoLogoFF.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 290, 205));

        panelXClose.setBackground(new java.awt.Color(11, 33, 56));

        btnclose.setBackground(new java.awt.Color(106, 140, 255));
        btnclose.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        btnclose.setForeground(new java.awt.Color(0, 0, 0));
        btnclose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnclose.setText("X");
        btnclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelXCloseLayout = new javax.swing.GroupLayout(panelXClose);
        panelXClose.setLayout(panelXCloseLayout);
        panelXCloseLayout.setHorizontalGroup(
            panelXCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnclose, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        panelXCloseLayout.setVerticalGroup(
            panelXCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelXCloseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(panelXClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 0, 60, -1));

        panelminimize.setBackground(new java.awt.Color(11, 33, 56));

        minimize.setBackground(new java.awt.Color(39, 53, 255));
        minimize.setFont(new java.awt.Font("Roboto Light", 0, 48)); // NOI18N
        minimize.setForeground(new java.awt.Color(0, 0, 0));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("-");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelminimizeLayout = new javax.swing.GroupLayout(panelminimize);
        panelminimize.setLayout(panelminimizeLayout);
        panelminimizeLayout.setHorizontalGroup(
            panelminimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelminimizeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelminimizeLayout.setVerticalGroup(
            panelminimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelminimizeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(panelminimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 0, 60, 40));

        BackGround.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 290, 540));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources_img/Logo-min (1) (1).png"))); // NOI18N
        BackGround.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 70));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(247, 127, 27));
        jLabel5.setText("EL YUNQUE");
        BackGround.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 140, 30));

        iniciarSesion.setBackground(new java.awt.Color(64, 64, 64));
        iniciarSesion.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        iniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        iniciarSesion.setText("INICIAR SESIÒN");
        BackGround.add(iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 300, 50));

        jLabel8.setBackground(new java.awt.Color(64, 64, 64));
        jLabel8.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("CONTRASEÑA");
        BackGround.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 130, 30));

        txtUser.setBackground(new java.awt.Color(255, 255, 255));
        txtUser.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(153, 153, 153));
        txtUser.setText("Ingrese su nombre de usuario");
        txtUser.setBorder(null);
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUserMousePressed(evt);
            }
        });
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        BackGround.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 390, 30));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        BackGround.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 390, 10));

        jLabel9.setBackground(new java.awt.Color(64, 64, 64));
        jLabel9.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("USUARIO");
        BackGround.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 130, 30));

        paswordUser.setBackground(new java.awt.Color(255, 255, 255));
        paswordUser.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        paswordUser.setForeground(new java.awt.Color(153, 153, 153));
        paswordUser.setText("********");
        paswordUser.setBorder(null);
        paswordUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paswordUserMousePressed(evt);
            }
        });
        paswordUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paswordUserActionPerformed(evt);
            }
        });
        BackGround.add(paswordUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 390, 30));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        BackGround.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 390, 10));

        HeaderExit.setBackground(new java.awt.Color(255, 255, 255));
        HeaderExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderExitMouseDragged(evt);
            }
        });
        HeaderExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderExitMousePressed(evt);
            }
        });
        HeaderExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        BackGround.add(HeaderExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        btnIniciarSesion.setBackground(new java.awt.Color(32, 138, 215));
        btnIniciarSesion.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("INICIAR SESIÓN");
        btnIniciarSesion.setFocusPainted(false);
        btnIniciarSesion.setFocusable(false);
        btnIniciarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseExited(evt);
            }
        });
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        BackGround.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 390, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed

    }//GEN-LAST:event_txtUserActionPerformed

    /**
     * Capturar la posición del mouse al hacer clic para permitir mover la
     * ventana.
     */
    private void HeaderExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderExitMousePressed
        /* asignar las cordenadas del puntero del mouse, para saber donde se hace el clic de la interfaz grafica */
        xMouse = evt.getX();
        yMouse = evt.getY();

    }//GEN-LAST:event_HeaderExitMousePressed

    /**
     * Permite arrastrar la ventana con el mouse, actualizando su posición.
     */
    private void HeaderExitMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderExitMouseDragged

        /* se obtiene las cordenadas del mouse en la pantalla y se
        *  actualiza la posición de la ventana para que siga el movimiento del mouse,
        *  usando la diferencia entre las coordenadas actuales y la posición inicial del mouse al hacer clic.*/
        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();
        this.setLocation(X - xMouse, Y - yMouse);
    }//GEN-LAST:event_HeaderExitMouseDragged
    /**
     * Cerrar la aplicación cuando se hace clic en el botón de cerrar.
     */
    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btncloseMouseClicked

    /**
     * Cambia el color del botón cerrar cuando el mouse entra.
     */
    private void btncloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseEntered
        btnclose.setForeground(Color.WHITE);
        panelXClose.setBackground(Color.red);

    }//GEN-LAST:event_btncloseMouseEntered

    /**
     * Restaura el color del botón cerrar cuando el mouse sale.
     */
    private void btncloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseExited
        btnclose.setForeground(Color.BLACK);
        panelXClose.setBackground(new Color(11, 33, 56));

    }//GEN-LAST:event_btncloseMouseExited

    /**
     * Minimiza la ventana actual.
     */
    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked

        setState(JFrame.ICONIFIED);
        panelminimize.setBackground(new Color(39, 53, 255));
    }//GEN-LAST:event_minimizeMouseClicked

    /**
     * Cambia el color del botón minimizar al pasar el mouse.
     */
    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        panelminimize.setBackground(new Color(197, 200, 206));

    }//GEN-LAST:event_minimizeMouseEntered
    /**
     * Restaura el color del botón minimizar cuando el mouse sale.
     */
    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited

        panelminimize.setBackground(new Color(11, 33, 56));
    }//GEN-LAST:event_minimizeMouseExited

    /**
     * Ejecuta el botón de iniciar sesión al presionar Enter en el campo
     * contraseña.
     */
    private void paswordUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paswordUserActionPerformed

        btnIniciarSesion.doClick();
    }//GEN-LAST:event_paswordUserActionPerformed

    /**
     * Limpia el campo de usuario si contiene el texto por defecto.
     */
    private void txtUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMousePressed

        if (txtUser.getText().equals("Ingrese su nombre de usuario")) {
            txtUser.setText("");
            txtUser.setForeground(Color.BLACK);
        }
        if (String.valueOf(paswordUser.getPassword()).isEmpty()) {
            paswordUser.setText("********");
            paswordUser.setForeground(new Color(159, 159, 159));
        }

    }//GEN-LAST:event_txtUserMousePressed
    /**
     * Limpia el campo contraseña si contiene el texto por defecto.
     */
    private void paswordUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paswordUserMousePressed

        if (String.valueOf(paswordUser.getPassword()).equals("********")) {
            paswordUser.setText("");
            paswordUser.setForeground(Color.BLACK);
        }
        if (txtUser.getText().isEmpty()) {
            txtUser.setText("Ingrese su nombre de usuario");
            txtUser.setForeground(new Color(159, 159, 159));
        }

     }//GEN-LAST:event_paswordUserMousePressed
    /**
     * Lógica para validar las credenciales del usuario y abrir la ventana
     * principal.
     */
    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed

        String usuario = txtUser.getText();
        char[] contraseniachar = paswordUser.getPassword();
        String contrasenia = new String(contraseniachar);

        try {

            DAOUsuarios dao = new DAOUsuariosImpl();
            Usuario user = dao.validarUsuario(usuario, contrasenia);

            if (user != null) {

                new Principal(user).setVisible(true); // Crea y muestra la ventana principal
                this.dispose(); // Cierra la ventana actual

            } else {
                JOptionPane.showMessageDialog(this, "correo o contrasenia incorrecto\n Intentelo nuevamente", "", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {

            System.out.println(e.getMessage() + "Error al validar usuario");

        }


    }//GEN-LAST:event_btnIniciarSesionActionPerformed
    /**
     * Cambia el color del botón de iniciar sesión al pasar el mouse.
     */
    private void btnIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseEntered

        btnIniciarSesion.setBackground(new Color(16, 86, 148));
    }//GEN-LAST:event_btnIniciarSesionMouseEntered

    /**
     * Restaura el color del botón iniciar sesión cuando el mouse sale.
     */
    private void btnIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseExited
        btnIniciarSesion.setBackground(new Color(32, 138, 215));
    }//GEN-LAST:event_btnIniciarSesionMouseExited

    private void btnIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseClicked
    }//GEN-LAST:event_btnIniciarSesionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel HeaderExit;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel btnclose;
    private javax.swing.JLabel iniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel panelXClose;
    private javax.swing.JPanel panelminimize;
    private javax.swing.JPasswordField paswordUser;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

}
