/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistemadeventaseinventario.Presentacion.Modulos;

import com.mycompany.sistemadeventaseinventario.DAOImplementacion.DAOProductoImpl;
import com.mycompany.sistemadeventaseinventario.PersistenciaDAO.DAOProducto;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Frank
 */
public class Inicio extends javax.swing.JPanel {

    private DAOProducto daoProducto = new DAOProductoImpl();

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        mostrartablas();
    }

    public void InitStyles() {

    }

    private void mostrartablas() {

        DefaultTableModel tab1 = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        };

        DefaultTableModel tab2 = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        };

        String titulos[] = {"Codigo", "Producto", "Stock actual"};
        tab1.setColumnIdentifiers(titulos);
        tbprodBajosStock.setModel(tab1);
        tbprodBajosStock.getTableHeader().setReorderingAllowed(false);
        
        
        String titulos2[] = {"Codigo", "Producto", "Cantidad Vendida"};
        tab2.setColumnIdentifiers(titulos2);
        tbProductosMasVendidos.setModel(tab2);
        tbProductosMasVendidos.getTableHeader().setReorderingAllowed(false);

        cargarTablaBajoStock();
        cargarTablaMasVendidos();

    }

    private void cargarTablaBajoStock() {
        DefaultTableModel modelo = (DefaultTableModel) tbprodBajosStock.getModel();
        modelo.setRowCount(0); // Limpia la tabla de datos anteriores.

        try {
            List<Object[]> lista = daoProducto.listarBajoStock();
            for (Object[] fila : lista) {
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            System.err.println("Error al cargar productos con bajo stock: " + e.getMessage());
        }
    }

    private void cargarTablaMasVendidos() {
        DefaultTableModel modelo = (DefaultTableModel) tbProductosMasVendidos.getModel();
        modelo.setRowCount(0); // Limpia la tabla de datos anteriores.

        try {
            // Se mostrará el TOP 5 de los más vendidos.
            List<Object[]> lista = daoProducto.listarMasVendidos();
            for (Object[] fila : lista) {
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            System.err.println("Error al cargar productos más vendidos: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InicioPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProductosMasVendidos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbprodBajosStock = new javax.swing.JTable();
        lblProductosMasVendidos = new javax.swing.JButton();
        lblProdBajS = new javax.swing.JButton();

        InicioPanel.setBackground(new java.awt.Color(255, 255, 255));
        InicioPanel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        InicioPanel.setPreferredSize(new java.awt.Dimension(830, 423));

        tbProductosMasVendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbProductosMasVendidos);

        tbprodBajosStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tbprodBajosStock);

        lblProductosMasVendidos.setBackground(new java.awt.Color(255, 255, 255));
        lblProductosMasVendidos.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lblProductosMasVendidos.setForeground(new java.awt.Color(153, 255, 153));
        lblProductosMasVendidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources_img/dinero.png"))); // NOI18N
        lblProductosMasVendidos.setText("Productos más vendidos");
        lblProductosMasVendidos.setBorder(null);
        lblProductosMasVendidos.setIconTextGap(15);
        lblProductosMasVendidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductosMasVendidosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblProductosMasVendidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblProductosMasVendidosMouseExited(evt);
            }
        });
        lblProductosMasVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblProductosMasVendidosActionPerformed(evt);
            }
        });

        lblProdBajS.setBackground(new java.awt.Color(255, 255, 255));
        lblProdBajS.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lblProdBajS.setForeground(new java.awt.Color(255, 102, 102));
        lblProdBajS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources_img/advertencia (1).png"))); // NOI18N
        lblProdBajS.setText("Productos con bajo stock !!");
        lblProdBajS.setBorder(null);
        lblProdBajS.setIconTextGap(15);
        lblProdBajS.setMargin(new java.awt.Insets(10, 14, 10, 14));
        lblProdBajS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProdBajSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblProdBajSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblProdBajSMouseExited(evt);
            }
        });
        lblProdBajS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblProdBajSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InicioPanelLayout = new javax.swing.GroupLayout(InicioPanel);
        InicioPanel.setLayout(InicioPanelLayout);
        InicioPanelLayout.setHorizontalGroup(
            InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InicioPanelLayout.createSequentialGroup()
                        .addGroup(InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InicioPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblProdBajS, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                                .addGap(28, 28, 28)
                                .addComponent(lblProductosMasVendidos, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                            .addGroup(InicioPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))
                    .addGroup(InicioPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())))
        );
        InicioPanelLayout.setVerticalGroup(
            InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdBajS)
                    .addComponent(lblProductosMasVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InicioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InicioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblProductosMasVendidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosMasVendidosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProductosMasVendidosMouseClicked

    private void lblProductosMasVendidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosMasVendidosMouseEntered
    }//GEN-LAST:event_lblProductosMasVendidosMouseEntered

    private void lblProductosMasVendidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosMasVendidosMouseExited
    }//GEN-LAST:event_lblProductosMasVendidosMouseExited

    private void lblProductosMasVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblProductosMasVendidosActionPerformed


    }//GEN-LAST:event_lblProductosMasVendidosActionPerformed

    private void lblProdBajSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdBajSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProdBajSMouseClicked

    private void lblProdBajSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdBajSMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProdBajSMouseEntered

    private void lblProdBajSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdBajSMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProdBajSMouseExited

    private void lblProdBajSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblProdBajSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProdBajSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InicioPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton lblProdBajS;
    private javax.swing.JButton lblProductosMasVendidos;
    private javax.swing.JTable tbProductosMasVendidos;
    private javax.swing.JTable tbprodBajosStock;
    // End of variables declaration//GEN-END:variables
}
